<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UnitTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('unit')->delete();
        
        \DB::table('unit')->insert(array (
            0 => 
            array (
                'id' => 1,
                'outlet_id' => 1,
                'code' => 'KG',
                'name' => 'Kilogram',
                'base_unit' => 'KG',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:43:31',
                'updated_at' => '2025-02-24 10:43:31',
            ),
            1 => 
            array (
                'id' => 2,
                'outlet_id' => 1,
                'code' => 'BTL-500ML',
                'name' => 'Botol 500ML',
                'base_unit' => 'BTL',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:43:31',
                'updated_at' => '2025-02-24 10:43:31',
            ),
            2 => 
            array (
                'id' => 3,
                'outlet_id' => 1,
                'code' => 'PCK-500GR',
                'name' => 'Pack 500GR',
                'base_unit' => 'PCK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:43:31',
                'updated_at' => '2025-02-24 10:43:31',
            ),
            3 => 
            array (
                'id' => 4,
                'outlet_id' => 1,
                'code' => 'PCS',
                'name' => 'Pieces',
                'base_unit' => 'PCS',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:43:31',
                'updated_at' => '2025-02-24 10:43:31',
            ),
            4 => 
            array (
                'id' => 5,
                'outlet_id' => 1,
                'code' => 'CAN-227GR',
                'name' => 'Can 227GR',
                'base_unit' => 'CAN',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:43:31',
                'updated_at' => '2025-02-24 10:43:31',
            ),
            5 => 
            array (
                'id' => 6,
                'outlet_id' => 1,
                'code' => 'Karung',
                'name' => 'Karung',
                'base_unit' => 'KR',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            6 => 
            array (
                'id' => 7,
                'outlet_id' => 1,
                'code' => 'BTL-250ML',
                'name' => 'Botol 250ML',
                'base_unit' => 'BTL',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            7 => 
            array (
                'id' => 8,
                'outlet_id' => 1,
                'code' => 'BTL-130GR',
                'name' => 'Botol 130GR',
                'base_unit' => 'BTL',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            8 => 
            array (
                'id' => 9,
                'outlet_id' => 1,
                'code' => 'PCK-500GR',
                'name' => 'Pack 500GR',
                'base_unit' => 'PCK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            9 => 
            array (
                'id' => 10,
                'outlet_id' => 1,
                'code' => 'PCK-300GR',
                'name' => 'Pack 300GR',
                'base_unit' => 'PCK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            10 => 
            array (
                'id' => 11,
                'outlet_id' => 1,
                'code' => 'PCS',
                'name' => 'Pieces',
                'base_unit' => 'PCS',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            11 => 
            array (
                'id' => 12,
                'outlet_id' => 1,
                'code' => 'PACK-500GR',
                'name' => 'Pack 500GR',
                'base_unit' => 'PACK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            12 => 
            array (
                'id' => 13,
                'outlet_id' => 1,
                'code' => 'PCK-250GR',
                'name' => 'Pack 250GR',
                'base_unit' => 'PCK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            13 => 
            array (
                'id' => 14,
                'outlet_id' => 1,
                'code' => 'PCK-1KG',
                'name' => 'Pack 1KG',
                'base_unit' => 'PCK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            14 => 
            array (
                'id' => 15,
                'outlet_id' => 1,
                'code' => 'BTL-250ML',
                'name' => 'Botol 250ML',
                'base_unit' => 'BTL',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            15 => 
            array (
                'id' => 16,
                'outlet_id' => 1,
                'code' => 'PACK-275GR',
                'name' => 'Pack 275GR',
                'base_unit' => 'PACK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            16 => 
            array (
                'id' => 17,
                'outlet_id' => 1,
                'code' => 'BTL-8GR',
                'name' => 'Botol 8GR',
                'base_unit' => 'BTL',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            17 => 
            array (
                'id' => 18,
                'outlet_id' => 1,
                'code' => 'PCK-10GR',
                'name' => 'Pack 10GR',
                'base_unit' => 'PCK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            18 => 
            array (
                'id' => 19,
                'outlet_id' => 1,
                'code' => 'PCK-40GR',
                'name' => 'Pack 40GR',
                'base_unit' => 'PCK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            19 => 
            array (
                'id' => 20,
                'outlet_id' => 1,
                'code' => 'PCK-170GR',
                'name' => 'Pack 170GR',
                'base_unit' => 'PCK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            20 => 
            array (
                'id' => 21,
                'outlet_id' => 1,
                'code' => 'PCK-165GR',
                'name' => 'Pack 165GR',
                'base_unit' => 'PCK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            21 => 
            array (
                'id' => 22,
                'outlet_id' => 1,
                'code' => 'PCK-1LTR',
                'name' => 'Pack 1LTR',
                'base_unit' => 'PCK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            22 => 
            array (
                'id' => 23,
                'outlet_id' => 1,
                'code' => 'PCK-5SLICE',
                'name' => 'Pack 5 Slice',
                'base_unit' => 'PCK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            23 => 
            array (
                'id' => 24,
                'outlet_id' => 1,
                'code' => 'PACK-100GR',
                'name' => 'Pack 100GR',
                'base_unit' => 'PACK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            24 => 
            array (
                'id' => 25,
                'outlet_id' => 1,
                'code' => 'PACK-200GR',
                'name' => 'Pack 200GR',
                'base_unit' => 'PACK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            25 => 
            array (
                'id' => 26,
                'outlet_id' => 1,
                'code' => 'PACK-1KG',
                'name' => 'Pack 1KG',
                'base_unit' => 'PACK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            26 => 
            array (
                'id' => 27,
                'outlet_id' => 1,
                'code' => 'CAN-227GR',
                'name' => 'Can 227GR',
                'base_unit' => 'CAN',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            27 => 
            array (
                'id' => 28,
                'outlet_id' => 1,
                'code' => 'CAN-1000GR',
                'name' => 'Can 1000GR',
                'base_unit' => 'CAN',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            28 => 
            array (
                'id' => 29,
                'outlet_id' => 1,
                'code' => 'PAPAN',
                'name' => 'Papan',
                'base_unit' => 'PAPAN',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            29 => 
            array (
                'id' => 30,
                'outlet_id' => 1,
                'code' => 'BUAH',
                'name' => 'Buah',
                'base_unit' => 'BUAH',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            30 => 
            array (
                'id' => 31,
                'outlet_id' => 1,
                'code' => 'BTR',
                'name' => 'Butir',
                'base_unit' => 'BTR',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            31 => 
            array (
                'id' => 32,
                'outlet_id' => 1,
                'code' => 'SISIR',
                'name' => 'Sisir',
                'base_unit' => 'SISIR',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            32 => 
            array (
                'id' => 33,
                'outlet_id' => 1,
                'code' => 'LBR',
                'name' => 'Lembar',
                'base_unit' => 'LBR',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            33 => 
            array (
                'id' => 34,
                'outlet_id' => 1,
                'code' => 'LTR',
                'name' => 'Liter',
                'base_unit' => 'LTR',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            34 => 
            array (
                'id' => 35,
                'outlet_id' => 1,
                'code' => 'BOX-50PCS',
                'name' => 'Box 50PCS',
                'base_unit' => 'BOX',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            35 => 
            array (
                'id' => 36,
                'outlet_id' => 1,
                'code' => 'BAL',
                'name' => 'Bal',
                'base_unit' => 'BAL',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 10:49:16',
                'updated_at' => '2025-02-24 10:49:16',
            ),
            36 => 
            array (
                'id' => 37,
                'outlet_id' => 1,
                'code' => 'KG',
                'name' => 'Kilogram',
                'base_unit' => 'KG',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            37 => 
            array (
                'id' => 38,
                'outlet_id' => 1,
                'code' => 'BTL-500ML',
                'name' => 'Botol 500ML',
                'base_unit' => 'BTL',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            38 => 
            array (
                'id' => 39,
                'outlet_id' => 1,
                'code' => 'BTL-130GR',
                'name' => 'Botol 130GR',
                'base_unit' => 'BTL',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            39 => 
            array (
                'id' => 40,
                'outlet_id' => 1,
                'code' => 'PCK-500GR',
                'name' => 'Pack 500GR',
                'base_unit' => 'PCK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            40 => 
            array (
                'id' => 41,
                'outlet_id' => 1,
                'code' => 'PCK-300GR',
                'name' => 'Pack 300GR',
                'base_unit' => 'PCK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            41 => 
            array (
                'id' => 42,
                'outlet_id' => 1,
                'code' => 'PCS',
                'name' => 'Pieces',
                'base_unit' => 'PCS',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            42 => 
            array (
                'id' => 43,
                'outlet_id' => 1,
                'code' => 'PACK-500GR',
                'name' => 'Pack 500GR',
                'base_unit' => 'PACK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            43 => 
            array (
                'id' => 44,
                'outlet_id' => 1,
                'code' => 'PCK-250GR',
                'name' => 'Pack 250GR',
                'base_unit' => 'PCK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            44 => 
            array (
                'id' => 45,
                'outlet_id' => 1,
                'code' => 'PCK-1KG',
                'name' => 'Pack 1KG',
                'base_unit' => 'PCK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            45 => 
            array (
                'id' => 46,
                'outlet_id' => 1,
                'code' => 'BTL-250ML',
                'name' => 'Botol 250ML',
                'base_unit' => 'BTL',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            46 => 
            array (
                'id' => 47,
                'outlet_id' => 1,
                'code' => 'PACK-275GR',
                'name' => 'Pack 275GR',
                'base_unit' => 'PACK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            47 => 
            array (
                'id' => 48,
                'outlet_id' => 1,
                'code' => 'BTL-8GR',
                'name' => 'Botol 8GR',
                'base_unit' => 'BTL',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            48 => 
            array (
                'id' => 49,
                'outlet_id' => 1,
                'code' => 'PCK-10GR',
                'name' => 'Pack 10GR',
                'base_unit' => 'PCK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            49 => 
            array (
                'id' => 50,
                'outlet_id' => 1,
                'code' => 'PCK-40GR',
                'name' => 'Pack 40GR',
                'base_unit' => 'PCK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            50 => 
            array (
                'id' => 51,
                'outlet_id' => 1,
                'code' => 'PCK-170GR',
                'name' => 'Pack 170GR',
                'base_unit' => 'PCK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            51 => 
            array (
                'id' => 52,
                'outlet_id' => 1,
                'code' => 'PCK-165GR',
                'name' => 'Pack 165GR',
                'base_unit' => 'PCK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            52 => 
            array (
                'id' => 53,
                'outlet_id' => 1,
                'code' => 'PCK-1LTR',
                'name' => 'Pack 1LTR',
                'base_unit' => 'PCK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            53 => 
            array (
                'id' => 54,
                'outlet_id' => 1,
                'code' => 'PCK-5SLICE',
                'name' => 'Pack 5 Slice',
                'base_unit' => 'PCK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            54 => 
            array (
                'id' => 55,
                'outlet_id' => 1,
                'code' => 'PACK-100GR',
                'name' => 'Pack 100GR',
                'base_unit' => 'PACK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            55 => 
            array (
                'id' => 56,
                'outlet_id' => 1,
                'code' => 'PACK-200GR',
                'name' => 'Pack 200GR',
                'base_unit' => 'PACK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            56 => 
            array (
                'id' => 57,
                'outlet_id' => 1,
                'code' => 'PACK-1KG',
                'name' => 'Pack 1KG',
                'base_unit' => 'PACK',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            57 => 
            array (
                'id' => 58,
                'outlet_id' => 1,
                'code' => 'CAN-227GR',
                'name' => 'Can 227GR',
                'base_unit' => 'CAN',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            58 => 
            array (
                'id' => 59,
                'outlet_id' => 1,
                'code' => 'CAN-1000GR',
                'name' => 'Can 1000GR',
                'base_unit' => 'CAN',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            59 => 
            array (
                'id' => 60,
                'outlet_id' => 1,
                'code' => 'PAPAN',
                'name' => 'Papan',
                'base_unit' => 'PAPAN',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            60 => 
            array (
                'id' => 61,
                'outlet_id' => 1,
                'code' => 'BUAH',
                'name' => 'Buah',
                'base_unit' => 'BUAH',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            61 => 
            array (
                'id' => 62,
                'outlet_id' => 1,
                'code' => 'BTR',
                'name' => 'Butir',
                'base_unit' => 'BTR',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            62 => 
            array (
                'id' => 63,
                'outlet_id' => 1,
                'code' => 'SISIR',
                'name' => 'Sisir',
                'base_unit' => 'SISIR',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            63 => 
            array (
                'id' => 64,
                'outlet_id' => 1,
                'code' => 'LBR',
                'name' => 'Lembar',
                'base_unit' => 'LBR',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            64 => 
            array (
                'id' => 65,
                'outlet_id' => 1,
                'code' => 'LTR',
                'name' => 'Liter',
                'base_unit' => 'LTR',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            65 => 
            array (
                'id' => 66,
                'outlet_id' => 1,
                'code' => 'BOX-50PCS',
                'name' => 'Box 50PCS',
                'base_unit' => 'BOX',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
            66 => 
            array (
                'id' => 67,
                'outlet_id' => 1,
                'code' => 'BAL',
                'name' => 'Bal',
                'base_unit' => 'BAL',
                'operator' => '=',
                'operation_value' => '1',
                'is_active' => '1',
                'created_at' => '2025-02-24 14:22:07',
                'updated_at' => '2025-02-24 14:22:07',
            ),
        ));
        
        
    }
}